# Generated by Django 2.0.5 on 2018-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180507_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveryAddressId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productId',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to='images/productImages/'),
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
